version: '3.8'

services:
  # Клиент 1: Иван
  client_ivan:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: screen_monitor_ivan
    environment:
      - MACHINE_ID=Иван_Desktop
      - SERVER_HOST=195.133.17.131
      - SERVER_PORT=6789
      - SIMULATE_SCREEN=true
    restart: unless-stopped

  # Клиент 2: Мария
  client_maria:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: screen_monitor_maria
    environment:
      - MACHINE_ID=Мария_Laptop
      - SERVER_HOST=195.133.17.131
      - SERVER_PORT=6789
      - SIMULATE_SCREEN=true
    restart: unless-stopped

  # Клиент 3: Петр
  client_petr:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: screen_monitor_petr
    environment:
      - MACHINE_ID=Петр_Workstation
      - SERVER_HOST=195.133.17.131
      - SERVER_PORT=6789
      - SIMULATE_SCREEN=true
    restart: unless-stopped

  # Клиент 4: Анна
  client_anna:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: screen_monitor_anna
    environment:
      - MACHINE_ID=Анна_MacBook
      - SERVER_HOST=195.133.17.131
      - SERVER_PORT=6789
      - SIMULATE_SCREEN=true
    restart: unless-stopped

  # Клиент 5: Дмитрий
  client_dmitry:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: screen_monitor_dmitry
    environment:
      - MACHINE_ID=Дмитрий_PC
      - SERVER_HOST=195.133.17.131
      - SERVER_PORT=6789
      - SIMULATE_SCREEN=true
    restart: unless-stopped

